config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: "users#login"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
  get '/signout', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  get '/index' => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	devise :omniauthable, :omniauth_providers => [:facebook]

	def self.from_omniauth(auth)
      user = User.first_or_create(provider: auth.provider, uid: auth.uid)
      user.update(name: auth.info.name, email: auth.info.email, acces_token: auth.credentials.token)
      return user
  		#where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    	#user.email = auth.info.email
    	#user.name = auth.info.name
      #user.acces_token = auth.credentials.token
  		#end
	end

	def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"]
        #user.email = omniauth["extra"]["user_hash"]["email"]
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in @user#, :event => :authentication 
      #set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      redirect_to index_url

    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      #redirect_to new_user_registration_url
    end
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :user_id, :acces_token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :acces_token %><br>
    <%= f.text_field :acces_token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1></h1>

<img src="http://www.freelargeimages.com/wp-content/uploads/2014/11/Facebook_logo-6.jpg" alt="..." class="fblogo">

 <h3></h3>

<section class="log">

<div class="user">
  <tbody>
    <td><%= current_user.name %></td> -
    <td><%= current_user.email %></td> -
    <td><%= current_user.uid %></td>
  </tbody>
</div>
<br> <br> 

</section>
<a class="btn btn-primary" href=<%=destroy_user_session_url %> role="button">Logout</a>

app/views/users/login.html.erb
<h1></h1>
<img src="http://www.freelargeimages.com/wp-content/uploads/2014/11/Facebook_logo-6.jpg" alt="..." class="fblogo">

<a class="btn btn-primary btn-lg" href=<%=user_omniauth_authorize_path(:facebook)%> role="button">Login</a>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>Acces token:</strong>
  <%= @user.acces_token %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>